# Generated by Django 3.1.1 on 2022-04-05 13:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticPromotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='쿠폰 번호')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='전화번호')),
                ('total_times', models.SmallIntegerField(default=12, verbose_name='약정 회차')),
                ('left_times', models.SmallIntegerField(default=12, verbose_name='남은 회차')),
                ('sign_datetime', models.DateTimeField(verbose_name='가입일')),
                ('termination_datetime', models.DateTimeField(blank=True, null=True, verbose_name='해지일')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneticPromotionLogResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_file_excel', models.FileField(blank=True, null=True, upload_to='macrogen_settlement_result', verbose_name='정산 결과')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneticPromotionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=100, verbose_name='상품코드')),
                ('connection_client', models.CharField(max_length=100, verbose_name='거래처')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MacrogenSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='고객 전화번호')),
                ('order_id', models.CharField(max_length=100, verbose_name='주문번호')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료일사')),
                ('total_times', models.SmallIntegerField(default=12, verbose_name='약정 회차')),
                ('current_times', models.SmallIntegerField(default=0, verbose_name='당월 회차')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.customer')),
                ('genetic_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.geneticpromotion', verbose_name='프로모션')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneticPromotionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(verbose_name='주문 날짜')),
                ('order_time', models.TimeField(verbose_name='주문 시간')),
                ('action', models.CharField(choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '정기 결제 '), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('subscription_cancel', '구독 해지')], max_length=100, verbose_name='이벤트')),
                ('current_month_times', models.SmallIntegerField(default=0, verbose_name='결제 회차')),
                ('accumulate_times', models.SmallIntegerField(default=0, verbose_name='월별 누적')),
                ('billing_price', models.SmallIntegerField(default=0, verbose_name='청구 금액')),
                ('genetic_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.geneticpromotion', verbose_name='프로모션')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneticPromotionKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kit_code', models.CharField(blank=True, max_length=100, verbose_name='키트 번호')),
                ('coupon', models.CharField(blank=True, max_length=100, verbose_name='키트 번호')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('genetic_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.geneticpromotion', verbose_name='프로모션')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='geneticpromotion',
            name='promotion_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.geneticpromotionproduct', verbose_name='프로모션 상품'),
        ),
    ]
