# Generated by Django 3.1.1 on 2022-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0004_auto_20220406_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrogensettlement',
            name='status',
            field=models.CharField(choices=[('normal_proceeding', '정상 진행중'), ('normal_kit_return', '정상키트 반송'), ('break_kit_return', '파손키트 반송')], default='normal_proceeding', max_length=100, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='macrogensettlement',
            name='current_times',
            field=models.SmallIntegerField(default=1, verbose_name='당월 회차'),
        ),
    ]
