# Generated by Django 3.1.1 on 2022-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0006_auto_20220408_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneticpromotion',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='geneticpromotion',
            name='promotion_product',
        ),
        migrations.RemoveField(
            model_name='geneticpromotionkit',
            name='genetic_promotion',
        ),
        migrations.RemoveField(
            model_name='geneticpromotionlog',
            name='genetic_promotion',
        ),
        migrations.DeleteModel(
            name='GeneticPromotionLogResult',
        ),
        migrations.RemoveField(
            model_name='macrogensettlement',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='macrogensettlement',
            name='genetic_promotion',
        ),
        migrations.AddField(
            model_name='geneticpromotionproduct',
            name='total_times',
            field=models.SmallIntegerField(default=12, verbose_name='약정 회차'),
        ),
        migrations.DeleteModel(
            name='GeneticPromotion',
        ),
        migrations.DeleteModel(
            name='GeneticPromotionKit',
        ),
        migrations.DeleteModel(
            name='GeneticPromotionLog',
        ),
        migrations.DeleteModel(
            name='MacrogenSettlement',
        ),
    ]
