# Generated by Django 3.1.1 on 2022-04-12 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fruitdb', '0008_auto_20220411_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictestlog',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
