# Generated by Django 3.1.1 on 2022-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0009_genetictestlog_registrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genetictestkit',
            old_name='genetic_promotion',
            new_name='genetic_test',
        ),
        migrations.RemoveField(
            model_name='genetictestlog',
            name='accumulate_times',
        ),
        migrations.RemoveField(
            model_name='genetictestlog',
            name='current_month_times',
        ),
        migrations.AddField(
            model_name='genetictest',
            name='current_times',
            field=models.SmallIntegerField(default=0, verbose_name='결제 회차'),
        ),
        migrations.AlterField(
            model_name='genetictest',
            name='kit_status',
            field=models.CharField(choices=[('normal', '정상'), ('cancel', '정상 해지'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송')], default='normal', max_length=100, verbose_name='이벤트'),
        ),
    ]
