# Generated by Django 3.1.1 on 2022-04-13 15:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0011_genetictestkit_registrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='genetictestlog',
            name='action',
            field=models.CharField(choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '정기 결제 '), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('analyze_fail', '유전자검사 실패'), ('kit_resend', '유전자검사 키트 재발송'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('subscription_cancel', '구독 해지')], max_length=100, verbose_name='이벤트'),
        ),
    ]
