# Generated by Django 3.1.1 on 2022-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0012_auto_20220413_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='쿠폰 번호'),
        ),
    ]
