# Generated by Django 3.1.1 on 2022-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0014_genetictestproduct_month_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictestproduct',
            name='product_code',
            field=models.CharField(choices=[('normal', '정상'), ('cancel', '정상 해지'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송')], max_length=100, verbose_name='상품코드'),
        ),
    ]
