# Generated by Django 3.1.1 on 2022-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0015_auto_20220418_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictestproduct',
            name='connection_client',
            field=models.CharField(choices=[('1', '카카오'), ('999', '과일궁합')], max_length=100, verbose_name='거래처'),
        ),
        migrations.AlterField(
            model_name='genetictestproduct',
            name='product_code',
            field=models.CharField(max_length=100, verbose_name='상품코드'),
        ),
    ]
