# Generated by Django 3.1.1 on 2022-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0018_auto_20220422_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genetictest',
            old_name='current_times',
            new_name='kit_current_times',
        ),
        migrations.RenameField(
            model_name='genetictestlog',
            old_name='current_times',
            new_name='kit_current_times',
        ),
    ]
