# Generated by Django 3.1.1 on 2022-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0019_auto_20220422_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictest',
            name='is_kit_active',
            field=models.BooleanField(default=True, verbose_name='키트 정산 사용 여부'),
        ),
        migrations.AddField(
            model_name='genetictest',
            name='is_test_active',
            field=models.BooleanField(default=True, verbose_name='검사 정산 사용 여부'),
        ),
        migrations.AddField(
            model_name='genetictest',
            name='test_current_times',
            field=models.SmallIntegerField(default=0, verbose_name='검사 결제 회차'),
        ),
        migrations.AddField(
            model_name='genetictestlog',
            name='test_current_times',
            field=models.SmallIntegerField(default=0, verbose_name='검사 결제 회차'),
        ),
        migrations.AlterField(
            model_name='genetictest',
            name='kit_current_times',
            field=models.SmallIntegerField(default=0, verbose_name='키트 결제 회차'),
        ),
        migrations.AlterField(
            model_name='genetictestlog',
            name='kit_current_times',
            field=models.SmallIntegerField(default=0, verbose_name='키트 결제 회차'),
        ),
    ]
