# Generated by Django 3.1.1 on 2022-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0020_auto_20220422_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictestproduct',
            name='connection_client',
            field=models.CharField(choices=[('1', '카카오'), ('2', '고도몰'), ('999', '과일궁합')], max_length=100, verbose_name='거래처'),
        ),
    ]
