# Generated by Django 3.1.1 on 2022-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0021_auto_20220422_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='is_kit_active',
            field=models.BooleanField(default=False, verbose_name='키트 정산 사용 여부'),
        ),
        migrations.AlterField(
            model_name='genetictest',
            name='is_test_active',
            field=models.BooleanField(default=False, verbose_name='검사 정산 사용 여부'),
        ),
    ]
