# Generated by Django 3.1.1 on 2022-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0023_auto_20220425_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='genetictestkit',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주문번호'),
        ),
    ]
