# Generated by Django 3.1.1 on 2022-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0024_auto_20220509_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictest',
            name='is_kit_recept',
            field=models.BooleanField(default=False, verbose_name='키트 수신 여부'),
        ),
        migrations.AddField(
            model_name='genetictest',
            name='status',
            field=models.CharField(choices=[('normal', '정상'), ('cancel', '해지')], default='normal', max_length=100, verbose_name='상태'),
        ),
    ]
