# Generated by Django 3.1.1 on 2022-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0025_auto_20220509_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='current_times',
            field=models.IntegerField(default=0, verbose_name='결제 회차'),
        ),
        migrations.AlterField(
            model_name='genetictest',
            name='total_times',
            field=models.IntegerField(default=12, verbose_name='약정 회차'),
        ),
    ]
