# Generated by Django 3.1.1 on 2022-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0026_auto_20220510_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictestlog',
            name='billing_price',
            field=models.IntegerField(default=0, verbose_name='청구 금액'),
        ),
        migrations.AlterField(
            model_name='genetictestlog',
            name='current_times',
            field=models.IntegerField(default=0, verbose_name='결제 회차'),
        ),
    ]
