# Generated by Django 3.1.1 on 2022-05-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fruitdb', '0027_auto_20220510_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='JMFSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True, verbose_name='쿠폰 번호')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='주문번호')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('current_times', models.IntegerField(default=0, verbose_name='결제 회차')),
                ('total_times', models.IntegerField(default=12, verbose_name='약정 회차')),
                ('is_active', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.genetictestproduct', verbose_name='프로모션 상품')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JMFSubscriptionPaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateTimeField(verbose_name='주문 일시')),
                ('action', models.CharField(choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '할부'), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('analyze_fail', '유전자검사 실패'), ('kit_resend', '유전자검사 키트 재발송'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('subscription_cancel', '구독 해지')], max_length=100, verbose_name='이벤트')),
                ('billing_price', models.IntegerField(default=0, verbose_name='청구 금액')),
                ('current_times', models.IntegerField(default=0, verbose_name='결제 회차')),
                ('jmf_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.jmfsubscription', verbose_name='프로모션')),
                ('registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
