# Generated by Django 3.1.1 on 2022-05-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0029_auto_20220516_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='사용 여부'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='정렬순서'),
            preserve_default=False,
        ),
    ]
