# Generated by Django 3.1.1 on 2022-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0030_auto_20220516_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='is_url',
            field=models.BooleanField(default=True, verbose_name='링크 이동 여부'),
        ),
    ]
