# Generated by Django 3.1.1 on 2022-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0031_productbanner_is_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictestproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='상품 금액'),
        ),
        migrations.AddField(
            model_name='jmfsubscription',
            name='is_coupon_used',
            field=models.BooleanField(default=False, verbose_name='쿠폰 사용 여부'),
        ),
        migrations.AddField(
            model_name='jmfsubscription',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='이벤트 쿠폰 사용 여부'),
        ),
    ]
