# Generated by Django 3.1.1 on 2022-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0032_auto_20220517_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmfsubscription',
            name='sno',
            field=models.CharField(default=1, max_length=100, verbose_name='고도몰 일련번호'),
            preserve_default=False,
        ),
    ]
