# Generated by Django 3.1.1 on 2022-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0035_jmfsubscriptionlogresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmfsubscriptionlogresult',
            name='result_file_excel',
            field=models.FileField(blank=True, null=True, upload_to='jmf_settlement_result', verbose_name='정산 결과'),
        ),
    ]
