# Generated by Django 3.1.1 on 2022-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0036_auto_20220524_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_choice_agree',
            field=models.BooleanField(default=False),
        ),
    ]
