# Generated by Django 3.1.1 on 2022-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0037_customer_is_choice_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_choice_agree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
