# Generated by Django 3.1.1 on 2022-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0037_customer_is_choice_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictest',
            name='sno',
            field=models.CharField(default='', max_length=100, verbose_name='고도몰 일련번호'),
            preserve_default=False,
        ),
    ]
