# Generated by Django 3.1.1 on 2022-05-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0038_genetictest_sno'),
        ('fruitdb', '0038_auto_20220524_1858'),
    ]

    operations = [
    ]
