# Generated by Django 3.1.1 on 2022-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0041_auto_20220525_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmfsubscription',
            name='coupon_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='쿠폰 만료일시'),
        ),
        migrations.AddField(
            model_name='jmfsubscription',
            name='kit_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='쿠폰 만료일시'),
        ),
        migrations.AddField(
            model_name='jmfsubscription',
            name='test_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검사 시작일시'),
        ),
    ]
