# Generated by Django 3.1.1 on 2022-06-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0044_auto_20220530_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자 이름')),
                ('status', models.CharField(choices=[('contract', '약정 진행중'), ('coupon_bill_in_active', '중도 해지 쿠폰 미사용 청구'), ('coupon_refund_in_active', '중도 해지 쿠폰 사용 환급'), ('coupon_bill', '쿠폰 미사용 청구'), ('coupon_refund', '쿠폰 사용 환급'), ('kit_bill', '키트 미사용 청구'), ('kit_refund', '키트 사용 환급')], default='contract', max_length=100, verbose_name='상태')),
                ('price', models.IntegerField(default=0, verbose_name='금액')),
                ('jmf_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruitdb.jmfsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
