# Generated by Django 3.1.1 on 2022-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0045_billstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictest',
            name='is_kit_settlement',
            field=models.BooleanField(default=False, verbose_name='키트 수신 여부'),
        ),
    ]
