# Generated by Django 3.1.1 on 2022-06-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0046_genetictest_is_kit_settlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genetictestkit',
            name='genetic_test',
        ),
        migrations.RemoveField(
            model_name='genetictestkit',
            name='registrant',
        ),
        migrations.RemoveField(
            model_name='genetictestlog',
            name='genetic_test',
        ),
        migrations.RemoveField(
            model_name='genetictestlog',
            name='registrant',
        ),
        migrations.DeleteModel(
            name='GeneticTest',
        ),
        migrations.DeleteModel(
            name='GeneticTestKit',
        ),
        migrations.DeleteModel(
            name='GeneticTestLog',
        ),
    ]
