# Generated by Django 3.1.1 on 2022-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0049_auto_20220608_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='genetictestkit',
            name='invoice_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발송일시'),
        ),
    ]
