# Generated by Django 3.1.1 on 2022-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0050_genetictestkit_invoice_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='kit_status',
            field=models.CharField(choices=[('normal', '정상'), ('cancel', '정상 해지'), ('cancel_request', '키트 취소 신청'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('test_start_cancel', '검사 시작 후 취소')], default='normal', max_length=100, verbose_name='이벤트'),
        ),
        migrations.AlterField(
            model_name='genetictestlog',
            name='action',
            field=models.CharField(choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '할부'), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('cancel_request', '키트 취소 신청'), ('test_cancel', '유전자검사 취소'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('analyze_fail', '유전자검사 실패'), ('kit_resend', '유전자검사 키트 재발송'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_cancel', '정상 키트 취소'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('test_start_cancel', '검사 시작 후 취소'), ('subscription_cancel', '구독 해지')], max_length=100, verbose_name='이벤트'),
        ),
        migrations.AlterField(
            model_name='jmfsubscriptionpaymentlog',
            name='action',
            field=models.CharField(choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '정기결제'), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('analyze_fail', '유전자검사 실패'), ('kit_resend', '유전자검사 키트 재발송'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_cancel', '정상 키트 취소'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송'), ('subscription_cancel', '구독 해지')], max_length=100, verbose_name='이벤트'),
        ),
    ]
