# Generated by Django 3.1.1 on 2022-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0052_auto_20220616_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmfsubscription',
            name='sub_type',
            field=models.CharField(choices=[('0', '유전자 프로모션 관련 구독'), ('1', '이벤트 쿠폰(특정금액 구매)'), ('2', '고도몰 구독상품'), ('3', '쿠폰 임의발급 상품')], default=0, max_length=100, verbose_name='구독 타입'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jmfsubscription',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='이벤트 쿠폰 여부'),
        ),
    ]
