# Generated by Django 3.1.1 on 2022-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0053_auto_20220620_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
