# Generated by Django 3.1.1 on 2022-06-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0054_customer_app_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='app_version',
        ),
    ]
