# Generated by Django 3.1.1 on 2022-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitdb', '0056_customer_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmfsubscriptionpaymentlog',
            name='status',
            field=models.CharField(choices=[('paid', '정상결제'), ('refund', '환불')], default='paid', max_length=100, verbose_name='지불 상태'),
        ),
        migrations.AlterField(
            model_name='jmfsubscriptionpaymentlog',
            name='action',
            field=models.CharField(blank=True, choices=[('order_request', '주문'), ('order_confirmed', '주문확정 수신'), ('subscription', '정기결제'), ('test_agree', '유전자검사 동의'), ('test_request', '유전자검사 신청'), ('kit_send', '유전자검사 키트발송'), ('kit_recept', '유전자검사 키트수신'), ('analyze_fail', '유전자검사 실패'), ('kit_resend', '유전자검사 키트 재발송'), ('result_regist', '유전자검사 결과등록'), ('cancel_request', '취소 접수'), ('normal_kit_cancel', '정상 키트 취소'), ('normal_kit_return', '정상 키트 반송'), ('damaged_kit_return', '파손 키트 반송 혹은 미반송'), ('subscription_cancel', '구독 해지')], max_length=100, null=True, verbose_name='이벤트'),
        ),
    ]
